services:
  - type: web
    name: BLOG_PROJECT
    runtime: python
    startCommand: "gunicorn blog.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: 'DBurl'
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.9.0